# Generated by Django 4.2 on 2023-12-10 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salon.branch'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('thumbanail', models.ImageField(blank=True, null=True, upload_to='service_package')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('services', models.ManyToManyField(to='salon.service')),
            ],
        ),
    ]
