# Generated by Django 4.2 on 2023-12-17 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='service',
            new_name='services',
        ),
    ]
