# Generated by Django 4.2 on 2023-12-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_rename_service_booking_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received')], max_length=20),
        ),
    ]
