# Generated by Django 4.2 on 2023-12-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_service_branch_servicepackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'FeMale'), ('TRANSGENDER', 'Transgender')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(help_text='Date on which customer want service'),
        ),
    ]
