# Generated by Django 4.2 on 2023-12-10 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_booking_dob_booking_gender_booking_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='assigned_person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='services',
            field=models.ManyToManyField(to='salon.service'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('TRANSGENDER', 'Transgender')], max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
