# Generated by Django 4.2 on 2023-12-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_alter_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
