# Generated by Django 4.2 on 2023-12-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_remove_booking_date_booking_assigned_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
