# Generated by Django 4.2 on 2023-12-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_booking_booking_source_booking_remark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='branch',
        ),
    ]
